add_like = "Проставить лайки"
visit = "Просмотр"
add_to_cart = "Добавить в корзину"
add_and_remove_from_cart = "Добавить и убрать из корзины"
add_to_cart_and_order = "Добавить в корзину и заказать"
add_comment = "Комментарий"
add_comment_with_comparison = "Комментарий с сравнением"
