POST localhost:8000/task_group
Content-Type: application/json

{
  "task_type": "Проставить лайки",
  "target_type": "По артикулу",
  "target_value": "11127342\n111864727\n5024530\n9390267\n38415567\n3912338",
  "amount": 100,
  "days": 0,
  "hours": 0,
  "minutes": 1,
  "seconds": 0
}

###
GET localhost:8000/task_group?offset=0&limit=10