POST localhost:8000/task_group
Content-Type: application/json

{
  "task_type": "Проставить лайки",
  "target_type": "По магазину",
  "target_value": "586414",
  "amount": 100,
  "days": 0,
  "hours": 0,
  "minutes": 1,
  "seconds": 0
}

###
GET localhost:8000/task_group?offset=0&limit=10


###
GET localhost:8000/task_group/short?offset=0&limit=10